# Header

# 自己补充
#favicon:
 # small: ./img/favicon-16x16-next.ico
 # medium: ./img/favicon-32x32-next.ico
  #apple_touch_icon: /images/apple-touch-icon-next.png
  #safari_pinned_tab: /images/logo.svg
  #android_manifest: /images/manifest.json
  #ms_browserconfig: /images/browserconfig.xml
#menu_settings:
#  icons: true
# badges: false

menu:
  主页: /
  岁月: /archives
 # 我的: /about
# rss: /atom.xml
github: https://github.com/baijingfeng
logo_title: M
blog_title: Bai's Blog

# Content
excerpt_link: Read More
fancybox: true
mathjax: false

# Sidebar
sidebar: right
widgets:
- recent_posts
- tag
- archives

# Miscellaneous
wx_block: false
google_analytics:
favicon:
twitter:
google_plus:
fb_admins:
fb_app_id:

# Duoshuo
duoshuo_shortname:

# Swiftype Search
swiftype_key:


